
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[145] =
    {   0,
        0,    0,   40,   39,   15,   37,    4,   39,    2,   39,
       39,    8,    2,    2,   11,    1,    2,   13,   10,   12,
        3,    5,    3,    7,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,    9,   39,
       39,   15,    3,    0,   14,    0,    0,    5,    4,    0,
        0,    0,    6,    0,   15,   13,   38,   38,   38,   38,
       38,   23,   38,   38,   38,   38,   17,   38,   38,   38,
       38,   38,   38,   38,   38,   38,    7,   14,   14,    0,
        0,    0,   15,   38,   38,   38,   38,   38,   38,   26,
       38,   38,   28,   38,   38,   38,   38,   38,   38,   34,

       38,    0,    0,   15,   38,   38,   20,   38,   24,   38,
       38,   38,   29,   38,   38,   38,   38,   33,   38,   16,
        0,    0,   38,   19,   38,   25,   38,   30,   36,   38,
       38,   38,   35,   38,   38,   38,   31,   21,   32,   18,
       22,   38,   27,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   25,   24,   24,   24,   24,   24,   24,   24,
        1,   26,    1,    1,   27,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   24,   37,   38,   24,   39,
       40,   41,   24,   42,   43,   44,   45,   46,   47,   24,
       24,   24,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       51,    1,    1,   52,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    3,    3,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[152] =
    {   0,
        0,    0,  209,  210,  206,  210,  186,   48,  185,   47,
       47,  210,  184,   44,  210,   43,   50,  187,  210,  210,
      182,  181,  180,  210,    0,   18,  172,   27,  161,   41,
       37,  153,  155,  164,   28,  153,  166,  158,  210,   56,
      141,  189,  210,   73,  210,   74,   75,  210,  210,   76,
       77,   89,  210,   71,    0,  173,    0,  149,  156,  144,
      153,    0,  142,  146,  141,  143,    0,   54,  143,  144,
      135,  136,  141,  131,  133,  138,  210,  101,  102,  162,
       96,   83,    0,  134,  143,  138,  141,  136,  124,    0,
      136,  120,    0,  126,  124,  117,  125,  116,  127,    0,

      120,  102,  146,  210,  124,  118,    0,  109,    0,  121,
      108,  107,    0,  106,  107,  109,  117,    0,  107,  210,
      122,  108,  102,    0,   87,    0,   87,    0,    0,   83,
       87,   85,    0,   72,   65,   53,    0,    0,    0,    0,
        0,   48,    0,  210,  128,  131,   80,  134,  137,  140,
      143
    } ;

static const flex_int16_t yy_def[152] =
    {   0,
      144,    1,  144,  144,  144,  144,  144,  145,  144,  144,
      146,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  144,  144,
      144,  144,  144,  145,  144,  145,  145,  144,  144,  146,
      146,  146,  144,  148,  149,  144,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  144,  145,  146,  148,
      150,  148,  149,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,

      147,  150,  151,  144,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  144,
      151,  150,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,    0,  144,  144,  144,  144,  144,  144,
      144
    } ;

static const flex_int16_t yy_nxt[263] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   12,
       13,   14,   15,   16,    4,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   25,    4,    4,   25,   26,   27,
       28,   29,   30,   25,   25,   31,   25,   25,   32,   25,
       33,   34,   35,   36,   25,   37,   38,   39,   40,   39,
        4,   41,   45,   49,   45,   53,   53,   58,   61,   59,
       54,   51,   46,   48,   48,   55,   62,   48,   64,   67,
       48,   72,   52,   47,   73,   68,   48,   45,   45,   78,
       65,   81,   57,   45,   45,   66,  143,   46,   46,   46,
       51,   51,  142,   81,   92,   82,   79,   93,   47,   47,

       47,   52,   52,   51,   49,   45,  102,   82,  141,   45,
      140,  104,  102,   82,   52,   46,   51,  120,  122,  139,
      138,  137,  136,  120,  135,   82,   47,   52,   44,  134,
       44,   50,  122,   50,   80,   80,   80,   83,  133,   83,
      103,  103,  103,  121,  121,  121,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  102,  101,  100,   99,   98,   97,   96,   95,
       94,   91,   90,   89,   88,   87,   86,   85,   84,   56,
       42,   77,   76,   75,   74,   71,   70,   69,   63,   60,

       43,   43,   43,   56,   48,   48,   43,   42,  144,    3,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144
    } ;

static const flex_int16_t yy_chk[263] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    8,   10,   11,   14,   16,   26,   28,   26,
       17,   11,    8,   16,   14,   17,   28,   10,   30,   31,
       17,   35,   11,    8,   35,   31,   40,   44,   46,   47,
       30,   54,  147,   50,   51,   30,  142,   44,   46,   47,
       50,   51,  136,   82,   68,   54,   52,   68,   44,   46,

       47,   50,   51,   52,   40,   78,   81,   82,  135,   79,
      134,   81,  102,   54,   52,   78,   79,  102,  122,  132,
      131,  130,  127,  122,  125,   82,   78,   79,  145,  123,
      145,  146,  121,  146,  148,  148,  148,  149,  119,  149,
      150,  150,  150,  151,  151,  151,  117,  116,  115,  114,
      112,  111,  110,  108,  106,  105,  103,  101,   99,   98,
       97,   96,   95,   94,   92,   91,   89,   88,   87,   86,
       85,   84,   80,   76,   75,   74,   73,   72,   71,   70,
       69,   66,   65,   64,   63,   61,   60,   59,   58,   56,
       42,   41,   38,   37,   36,   34,   33,   32,   29,   27,

       23,   22,   21,   18,   13,    9,    7,    5,    3,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "LEXICO.l"
#line 2 "LEXICO.l"
#define IF     1
#define BOOLEAN     2
#define BREAK     3
#define CASE     4
#define STRING     5
#define DEFAULT     6
#define DO     7
#define ELSE     8
#define FALSEE     9
#define FOR     10
#define FUNCTION     11
#define INT     12
#define NULLL     13
#define INPUT     14
#define RETURN     15
#define SWITCH     16
#define TRUEE     17
#define VAR     18
#define WHILE     19
#define PRINT     20
#define CADENA     21
#define PARENTESIS 22
#define OpAritmetico 23
#define OpRelacion 24
#define OpLogico 25
#define OpAsignacion 26
#define OpAutoIncrementoDecremento 27
#define Llave 28
#define IDENTIFICADOR 29
#define PUNTOCOMA 30
#define COMA 31
#define DOSPUNTOS 32
#define MENOS 33



//por ejemplo
#define TIPOBOOLEAN -1
#define TIPOSTRING -2
#define TIPOENTERO -3
#define TIPOVACIO -4
#define TIPOFUNCION -5
#define TIPOVOID -6



#define CONSTENTERA 100


#define ERR "./Error"
#define FICHERO "./tablaSimbolos"
#define PARSE "./parse"

#include "ts2006.h"
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
//#include "./Estructura.c"
struct Tokens {
   char* lexema;
   char* lexemaSintactico;
   int  tipo;
   char*  valor;
   int   valor2;
   int lineaDondeEsta;
  
} Token; 
#define SEMANTICO
#include "funciones_ayuda.h"

#line 624 "lex.yy.c"
#line 625 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 98 "LEXICO.l"

#line 844 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 145 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 210 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
#line 99 "LEXICO.l"
{printf("Reconocio EOf: %s\n",yytext); return 101; }
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 100 "LEXICO.l"
{printf("Menos\n%s\n",yytext) ; return MENOS;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 101 "LEXICO.l"
{printf("OpAritmetico: %s\n",yytext); return OpAritmetico; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 102 "LEXICO.l"
{printf("OpRelacion: %s\n",yytext); return OpRelacion; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 103 "LEXICO.l"
{printf("OpLogico: %s\n",yytext); return OpLogico; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 104 "LEXICO.l"
{printf("OpAsignacion: %s\n",yytext); return OpAsignacion; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 105 "LEXICO.l"
{printf("OpAutoIncrementoDecremento: %s\n",yytext); return OpAutoIncrementoDecremento;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 106 "LEXICO.l"
{printf("Interrogacion: %s\n",yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 107 "LEXICO.l"
{ printf("Parentesis: %s\n",yytext);    return PARENTESIS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 108 "LEXICO.l"
{printf("Llave\n%s\n",yytext); return Llave; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 109 "LEXICO.l"
{printf("DosPuntos: %s\n",yytext) ; return DOSPUNTOS;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 110 "LEXICO.l"
{printf("Coma\n%s\n",yytext) ; return COMA;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 111 "LEXICO.l"
{printf("PuntoComa: %s\n",yytext); return PUNTOCOMA;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 112 "LEXICO.l"
{if(atoi(yytext)<=32767)
                        { printf("Entero con valor: %s\n",yytext); return CONSTENTERA;}
       else; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 116 "LEXICO.l"
{printf("CadenaDeCaracteres: %s\n",yytext) ; return CADENA;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 117 "LEXICO.l"
{printf("lo caza: %s\n",yytext) ;}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 118 "LEXICO.l"
{printf("escribeeeeeeeeee: %s\n",yytext) ;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 119 "LEXICO.l"
{printf("Reconocio: %s\n",yytext) ; return     IF;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 120 "LEXICO.l"
{printf("Reconocio: %s\n",yytext); return BOOLEAN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 121 "LEXICO.l"
{printf("Reconocio: %s\n",yytext); return BREAK;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 122 "LEXICO.l"
{printf("Reconocio: %s\n",yytext); return CASE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 123 "LEXICO.l"
{printf("Reconocio: %s\n",yytext); return STRING;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 124 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return DEFAULT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 125 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return DO;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 126 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return ELSE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 127 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return FALSEE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 128 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return FOR;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 129 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return FUNCTION;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 130 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return INT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 131 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return NULLL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 132 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return INPUT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 133 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return RETURN;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 134 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return SWITCH;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 135 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return TRUEE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 136 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return VAR;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 137 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return WHILE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 138 "LEXICO.l"
{printf("Reconocio: %s\n",yytext);return PRINT;}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 139 "LEXICO.l"
{ yylineno++; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 140 "LEXICO.l"
{printf("Idenetificador con nombre :%s\n",yytext); return IDENTIFICADOR;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 141 "LEXICO.l"
ECHO;
	YY_BREAK
#line 1104 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 145 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 145 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 144);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 141 "LEXICO.l"

char* siguienteToken;
int indiceReglas=0;
int tablaGlobal;
int tablaLocal;
int tablaActual;
int tablas[100];
int indiceTablas=0;
int desplgeneral=0;
int desplfuncion=0;
int flagDeclaracionUso;
int indiceSintactico = 0;
int reglas[1000];
struct Tokens s1[1000];
struct Tokens sgtetoken;
int dentroFuncion=0;
int dentroDeReturn=0;
char  ultimoLexema[20];
int tipoRetornoActual;
int elTipoElegido;


char listIdentificadores[100][20] ;
int IndiceListaIdentificadores=0;
int indiceLista2=0;


const char* var1="var";
const char* if1="if";
const char* while1="while";
const char* identificador1="identificador";
const char* return1="return";
const char* print1="print";
const char* input1="input";
const char* masmas="++";
const char* menosmenos="--";
const char* parentesisA="(";
const char* exclamacion="!";
const char* doo="do";
const char* puntocoma1=";";
const char* function1="function";
const char* Eof1="Eof";//implementar

const char* intt ="int";
const char* cadena ="cadena";
const char* enteroo ="entero";
const char* truee ="true";
const char* falsee ="false";
const char* boolean1="boolean";
const char* strings="string";
const char* yy="&&";
const char* oo="||";
const char* mas="+";
const char* menos="-";
const char* por="*";
const char* division="/";
const char* iguall="=";
const char* comaa=",";
const char* parentesisC=")";
const char* igualigual="==";


static char* amain[11];
static char* bmain[11];
static char* cmain[11];
static char* dmain[11];
static char* emain[11];
static char* fmain[11];
static char* gmain[11];
static char* hmain[11];
static char* imain[11];
static char* jmain[11];
static char* kmain[11];
static char* lmain[11];
static char* nmain[11];
static char* zmain[11];
/*static char* amain[5];
static char* bmain[11];
static char* cmain[3];
static char* dmain[7];
static char* emain[7];
static char* fmain[3];
static char* gmain[3];
static char* hmain[7];
static char* imain[6];
static char* jmain[7];
static char* kmain[4];
static char* lmain[5];
static char* nmain[6];*/
/*
    char *b[9];
    b[0]=var1;
    b[1]=if1;
    b[2]=while1;
    b[3]=if1;
    b[4]=identificador1;
    b[5]=return1;*/

int comparar();
int errorSintactico();
void equiparar();
void aadirRegla();
void buscarSiguietneToken();
/*void P();
void B();
void Bp();
void Bpp();
void T();
void S();
void Sp();
void S2();
void S3();
void S4();
void X();
void C();
void F();
void H();
void A();
void K();
void L();
void Q();
void E();
void Ep();
void Epp();
void R();
void Rp();
void U();
void Up();
void Upp();
void V();
void Vp();*/

int axioma();
int A(Typito * A_devuelvo);
int SIMPLE();
int TIPO();
int W();
int A2();
int B();
int J();
int K();
int V();
int H();
int X();
int Z();
int R();
int R1();
int E();
int S();
int T();
int O1();
int O2();
int O3();
int G();

int comparar(char * a, char * b[], int t) {
  int sol = 1;

  for (int i = 0; i < t; i++) {

    if (strcmp(a, b[i]) == 0) {
      sol = 0;
      //printf("COMPARA CON UN FIRST (%s,%s)\n",a,b[i]);
      break;
    }
  }
  return sol;
}

int errorSintactico() {
    
  printf("errorSintactico(): nos hemos encontrado con siguienteToken: %s, en la linea %i\n", siguienteToken,sgtetoken.lineaDondeEsta);
  exit(1);
}

void aadirRegla(int a) {
  reglas[indiceReglas] = a;
  indiceReglas++;
}

void equiparar(char * token) {
  if (strcmp(siguienteToken, token) != 0) {
    printf("MALLLL EKIPARADOOOOOOOOOOOOOOOOOOOOOOO (%s,%s) \n",siguienteToken,token);
    errorSintactico();

  }

  if (strcmp(siguienteToken, "Eof") != 0) {
    
    printf("BIEN EQUIPARADO (%s,%s)\n",siguienteToken,"Eof");
    buscarSiguietneToken();

  } else siguienteToken = "Eof";

}

void buscarSiguietneToken() {
  printf("Ejecuta Buscar Siguiente Token :\n");
  char prueba[100];
  int tipoLexico = sgtetoken.tipo;
  int lineaToken = sgtetoken.lineaDondeEsta;

  switch (tipoLexico) {
  case VAR:

    siguienteToken = "var";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;

  case DOSPUNTOS:

    siguienteToken = ";";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case COMA:

    siguienteToken = ",";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case MENOS:

    siguienteToken = "-";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case PUNTOCOMA:

    siguienteToken = ";";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case IDENTIFICADOR:

    siguienteToken = "identificador";
    strcpy(ultimoLexema, "");
    //ultimoLexema=s1[indiceSintactico].lexemaSintactico; //s1[i].lexemaSintactico
    //ultimoLexema=listIdentificadores[indiceLista2];	

    strcpy(ultimoLexema, listIdentificadores[indiceLista2]);
    printf("Identificador con lexema: %s\n", ultimoLexema);
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);

    indiceLista2++;
    break;
  case PARENTESIS:
    if (sgtetoken.valor2 == 1) {
      siguienteToken = "(";
      printf("\tque es: %s\n", siguienteToken);
      printf("\tlinea: %d\n", lineaToken);
      break;
    } else {
      siguienteToken = ")";
      printf("\tque es: %s\n", siguienteToken);
      printf("\tlinea: %d\n", lineaToken);
      break;
    }

  case OpAritmetico:

    if (sgtetoken.valor2 == 1) {
      siguienteToken = "+";
    }
    if (sgtetoken.valor2 == 2) {
      siguienteToken = "-";
    }
    if (sgtetoken.valor2 == 3) {
      siguienteToken = "*";
    }
    if (sgtetoken.valor2 == 4) {
      siguienteToken = "/";
    }
    if (sgtetoken.valor2 == 5) {
      siguienteToken = "%";
    }
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case OpRelacion:
    if (sgtetoken.valor2 == 1) {
      siguienteToken = "==";
    }
    if (sgtetoken.valor2 == 2) {
      siguienteToken = "!=";
    }
    if (sgtetoken.valor2 == 3) {
      siguienteToken = "<=";
    }
    if (sgtetoken.valor2 == 4) {
      siguienteToken = ">=";
    }
    if (sgtetoken.valor2 == 5) {
      siguienteToken = "<";
    }
    if (sgtetoken.valor2 == 6) {
      siguienteToken = ">";
    }
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case OpLogico:
    if (sgtetoken.valor2 == 1) {
      siguienteToken = "&&";
    }
    if (sgtetoken.valor2 == 2) {
      siguienteToken = "!";
    }
    if (sgtetoken.valor2 == 3) {
      siguienteToken = "||";
    }
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case OpAsignacion:
    if (sgtetoken.valor2 == 1) {
      siguienteToken = "=";
    }
    if (sgtetoken.valor2 == 2) {
      siguienteToken = "+=";
    }
    if (sgtetoken.valor2 == 3) {
      siguienteToken = "-=";
    }
    if (sgtetoken.valor2 == 4) {
      siguienteToken = "*=";
    }
    if (sgtetoken.valor2 == 5) {
      siguienteToken = "/=";
    }
    if (sgtetoken.valor2 == 6) {
      siguienteToken = "%=";
    }
    if (sgtetoken.valor2 == 7) {
      siguienteToken = "&=";
    }
    if (sgtetoken.valor2 == 8) {
      siguienteToken = "|=";
    }

    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);

    break;
  case OpAutoIncrementoDecremento:
    if (sgtetoken.valor2 == 1) {
      siguienteToken = "++";
    }
    if (sgtetoken.valor2 == 2) {
      siguienteToken = "--";
    }
    printf("\tlinea: %d\n", lineaToken);
    break;
  case Llave:
    if (sgtetoken.valor2 == 1) {
      siguienteToken = "{";
    }
    if (sgtetoken.valor2 == 2) {
      siguienteToken = "}";
    }
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;

  case IF:
    siguienteToken = "if";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;

  case BOOLEAN:
    siguienteToken = "boolean";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case BREAK:
    siguienteToken = "break";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case CASE:
    siguienteToken = "case";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case STRING:
    siguienteToken = "string";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case DEFAULT:
    siguienteToken = "default";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case DO:
    siguienteToken = "do";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case ELSE:
    siguienteToken = "else";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case FALSEE:
    siguienteToken = "false";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case FOR:
    siguienteToken = "for";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case FUNCTION:
    siguienteToken = "function";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;

  case INT:
    siguienteToken = "int";
    printf("\tlinea: %d\n", lineaToken);
    break;
  case NULLL:
    siguienteToken = "null";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case INPUT:
    siguienteToken = "input";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case RETURN:
    siguienteToken = "return";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case SWITCH:
    siguienteToken = "switch";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case TRUEE:
    siguienteToken = "true";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;

  case WHILE:
    siguienteToken = "while";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case PRINT:
    siguienteToken = "print";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;

  case CADENA:
    siguienteToken = "cadena";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case CONSTENTERA:
    siguienteToken = "entero";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  case 101:
    siguienteToken = "Eof";
    printf("\tque es: %s\n", siguienteToken);
    printf("\tlinea: %d\n", lineaToken);
    break;
  }

  //strcmp(siguienteToken,sgtetoken.lexemaSintactico);
  printf("\n me he cargado : %s  ` \n", siguienteToken);
  sgtetoken = s1[++indiceSintactico];
}


/*

















*/
/*
Axioma ->  { CrearTablGeneral , DentroFuncion = false dezp =0 ,     crearEstructuraDeTabasFunciones }     A { Imprimir y DestruirTGyTF }
*/

int axioma() {
  int resultadoOp;
  FILE * ficherito;

  tablaGlobal = crear_tabla();
  tablas[0] = tablaGlobal;
  indiceTablas++;
  tablaActual = tablaGlobal;
  Typito * A_nt = (Typito * ) malloc(sizeof(Typito));
  if (A(A_nt) == ERROR_SSS) {
    return ERROR_SSS;
  }
  if ( dameTipo(A_nt) != TIPO_OK) {
    return ERROR_SSS;
  }
printf("TERMINA SINTACTICO-SEMANTICO SATISFACTORIAMENTE, IMPRIME TOKENS Y TABLAS\n");
  /* para resetear lo que esta escrito*/
  ficherito = fopen(FICHERO, "w");
  // fprintf(ficherito, "Primera Tabla Que Se muestra es la tabla Global, las demas son de funciones: \n");
  fclose(ficherito);

  for (int i = 0; i < indiceTablas; i++) {

    resultadoOp = escribir_tabla(tablas[i], FICHERO);

    if (resultadoOp < 0) {
      printf("Error: %s\n", consultar_descripcion_ultimo_error());
    } else {
      printf("Se ha escrito bien");
    }

  }

  for (int i = 0; i < indiceTablas; i++) {
    destruir_tabla(tablas[i]);
  }
printf("\nDESTRUYE TABLAS\n");

}



int errorSemantico(){
printf("errorSemantico\n");
return 0;
}


#define SINTACTICOSEMANTICO
#include "funciones_Typito.h"

int analizadorSintactico()
{
printf("analisisSintacticoEjecutando\n");
buscarSiguietneToken();
if(axioma()==ERROR_SSS)
    exit(1);
return 0;
}
int yywrap() { 

 
 return 1;

}




void main(int argc, char *argv[])
{

	//inicializacion de los terminales para el sintactico para que se almacene en el stack y no en el heap;
	//para P amain:
	//SIMPLE
	amain[0] = (char *)input1;
	amain[1] = (char *)masmas;
	amain[2] = (char *)print1;
	amain[3] = (char *)return1;
	amain[4] = (char *)puntocoma1;
	amain[5] = (char *)identificador1;

	//Para B bmain:
	//first A
	bmain[0] = (char *)input1;
	bmain[1] = (char *)masmas;
	bmain[2] = (char *)print1;
	bmain[3] = (char *)return1;
	bmain[4] = (char *)puntocoma1;
	bmain[5] = (char *)var1;
	bmain[6] = (char *)if1;
	bmain[7] = (char *)identificador1;
	bmain[8] = (char *)doo;
	bmain[9] = (char *)function1;
	bmain[10] = (char *)Eof1;

	//Para Bp cmain:
	cmain[0] = (char *)intt;
	cmain[1] = (char *)strings;
	cmain[2] = (char *)boolean1;

	//Para X dmain:
	dmain[0] = (char *)parentesisA;
	dmain[1] = (char *)exclamacion;
	dmain[2] = (char *)identificador1;
	dmain[3] = (char *)enteroo;
	dmain[4] = (char *)cadena;
	dmain[5] = (char *)truee;
	dmain[6] = (char *)falsee;

	// Para C emain:
	emain[0] = (char *)var1;
	emain[1] = (char *)if1;
	emain[2] = (char *)doo;
	emain[3] = (char *)print1;
	emain[4] = (char *)identificador1;
	emain[5] = (char *)return1;
	emain[6] = (char *)input1;

	//Para H fmain:
	fmain[0] = (char *)intt;
	fmain[1] = (char *)boolean1;
	fmain[2] = (char *)strings;
	//Para A gmain:
	gmain[0] = (char *)doo;
	gmain[1] = (char *)Eof1;
	gmain[2] = (char *)function1;
	gmain[3] = (char *)identificador1;
	gmain[4] = (char *)return1;
	gmain[5] = (char *)input1;
	gmain[6] = (char *)var1;
	gmain[7] = (char *)if1;
	gmain[8] = (char *)masmas;
	gmain[9] = (char *)puntocoma1;
	gmain[10] = (char *)print1;

	//Para L hmain:
	hmain[0] = (char *)parentesisA;
	hmain[1] = (char *)exclamacion;
	hmain[2] = (char *)identificador1;
	hmain[3] = (char *)enteroo;
	hmain[4] = (char *)cadena;
	hmain[5] = (char *)truee;
	hmain[6] = (char *)falsee;

	//Para E imain:
	imain[0] = (char *)identificador1;
	imain[1] = (char *)enteroo;
	imain[2] = (char *)cadena;
	imain[3] = (char *)parentesisA;
	imain[4] = (char *)truee;
	imain[5] = (char *)falsee;

	//Para Epp jmain:
	jmain[0] = (char *)truee;
	jmain[1] = (char *)falsee;
	jmain[2] = (char *)cadena;
	jmain[3] = (char *)identificador1;
	jmain[4] = (char *)parentesisA;
	jmain[5] = (char *)menos;
	jmain[6] = (char *)enteroo;

	//Para R kmain:
	kmain[0] = (char *)puntocoma1;
	kmain[1] = (char *)parentesisC;
	kmain[2] = (char *)comaa;

	//Para U lmain:
	lmain[0] = (char *)puntocoma1;
	lmain[1] = (char *)yy;
	lmain[2] = (char *)parentesisC;
	lmain[3] = (char *)comaa;

	//Para Upp nmain:
	nmain[0] = (char *)puntocoma1;
	nmain[1] = (char *)yy;
	nmain[2] = (char *)parentesisC;
	nmain[3] = (char *)comaa;
	nmain[4] = (char *)igualigual;

	//
	zmain[0] = (char *)mas;	//bien
	zmain[1] = (char *)comaa;
	zmain[2] = (char *)yy;
	zmain[3] = (char *)puntocoma1;	//bien
	zmain[4] = (char *)igualigual;
	zmain[5] = (char *)parentesisC;	//bien

	/*const char* var1="var";
	const char* if1="if";
	const char* while1="while";
	const char* identificador1="identificador";
	const char* return1="return";
	const char* print1="print";
	const char* input1="input";
	const char* masmas="++";
	const char* menosmenos="--";
	const char* parentesisA="(";
	const char* exclamacion="!";

	const char* intt ="int";
	const char* cadena ="cadena";
	const char* truee ="true";
	const char* falsee ="false";
	const char* booleaneaneanl="booleaneanean";
	const char* strings="string";
	const char* yy="&&";
	const char* oo="||";
	const char* mas="+";
	const char* menos="-";
	const char* por="*";
	const char* division="/";
	const char* modulo="%";

	*/

	FILE * fichero;
	fichero = fopen("./token.txt", "w");
	
    FILE * ficheroDraco;
	ficheroDraco = fopen("./tokendraco.txt", "w");

	FILE * parse;
	parse = fopen("./parse.txt", "w");

    int fd=0;
	//fd=open("./token.txt",777);
	int ret;
	//variable que me guarda el numero de linea del error
	int error = yylineno;
	//creamos la tabla de simbolos

	//necesitamos crear unas variables globales para gestionar las tablas de simbolo

	int contador = 0;

//////////////////////////////////////////////////
        if(argc != 2)
        {
                fprintf(stderr,"Uso: ./aplicacion nombre_archivo\n");
                exit(1);
        }

        yyin = fopen(argv[1],"r");
        if(yyin == NULL)
        {
                fprintf(stderr,"No se puede abrir el archivo: %s\n",argv[1]);
                exit(0);
        }

        
///////////////////////////////////////////////////////////////
	while ((ret = yylex()) != 0)
	{

		switch (ret)
		{

			case DOSPUNTOS:
				s1[contador].tipo = DOSPUNTOS;
				s1[contador].lexema = "dosPuntos";
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lineaDondeEsta = yylineno;
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case MENOS:

				s1[contador].tipo = MENOS;
				s1[contador].lexema = "-";
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lineaDondeEsta = yylineno;
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case COMA:
				s1[contador].tipo = COMA;
				s1[contador].lexema = "Coma";
				s1[contador].lineaDondeEsta = yylineno;
				s1[contador].lexemaSintactico = yytext;
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case PUNTOCOMA:
				s1[contador].tipo = PUNTOCOMA;
				s1[contador].lexema = "PuntoComa";
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lineaDondeEsta = yylineno;
				printf("%s111111\n", s1[contador].lexemaSintactico);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case 101:
				s1[contador].tipo = 101;
				s1[contador].lexemaSintactico = "Eof";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%s11\n", s1[contador].lexemaSintactico);

				fprintf(fichero, "<eof,->\n");
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				printf("salidellexico\n");
				sgtetoken = s1[0];

				printf("********antes de ejecutar el sintactico******\n");
				for (int i = 0; i < IndiceListaIdentificadores; i++)
				{
					printf("%s\n", listIdentificadores[i]);
				}
				analizadorSintactico();
				printf("Descendente Recursivo\n");
               // printf("¡¡¡¡HA TERMINADO TODO!!!!, SALVO EL PARSE: Ahora comenzaria a escribir el parse... pero da error...\n");
/////////////////////////////////////////////////////////////////////////////////////SE DETIENE AQUI
               
               fprintf(parse,"DescendenteRecursivo\n");
                printf("\nSE HA ESCRITO EN PARSE la frase \"Descendente Recursivo\"\n");
				for (int i = 0; i < indiceReglas; i++)
				{
					fprintf(parse, "%i ", reglas[i]);
				}
                printf("\nSE HA ESCRITO EL PARSE\n");
				//analizadorSemantico();

				exit(0);

			case IDENTIFICADOR:

				

				s1[contador].tipo = IDENTIFICADOR;

				//valor2 nos da la posicion de la tabla
				// s1[contador].valor2=buscar_posicion_entrada(tabla,yytext);
				//
				//char[100][20] listIdentificadores;
				// int IndiceListaIdentificadores;

				strcpy(listIdentificadores[IndiceListaIdentificadores], yytext);

				s1[contador].lexema = "identificador";
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lineaDondeEsta = yylineno;
			
				printf("%d+\n", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,%d>\n", s1[contador].lexema, s1[contador].valor2);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				IndiceListaIdentificadores++;
				break;

			case PARENTESIS:
				s1[contador].tipo = PARENTESIS;
				s1[contador].lineaDondeEsta = yylineno;
				s1[contador].lexema = "PARENTESIS";
				s1[contador].lexemaSintactico = yytext;
				printf("%s+", s1[contador].lexemaSintactico);
				char bbbb;
				if (strcmp(yytext, ")") != 0)
				{
					bbbb = '1';
					s1[contador].valor2 = 1;
					fprintf(ficheroDraco, "<%d,%c>\n", s1[contador].tipo, bbbb);
				}
				else
				{
					s1[contador].valor2 = 2;
					bbbb = '2';
					fprintf(ficheroDraco, "<%d,%c>\n", s1[contador].tipo, bbbb);
				}

				printf("%d+", s1[contador].tipo);
				printf("%d\n", s1[contador].valor2);
				fprintf(fichero, "<%s,%d>\n", s1[contador].lexema, s1[contador].valor2);

				contador++;

				break;

			case OpAritmetico:
				s1[contador].tipo = OpAritmetico;
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lexema = "OpAritmetico";
				s1[contador].lineaDondeEsta = yylineno;

				if (strcmp(yytext, "+") == 0)
				{
					s1[contador].valor2 = 1;
				}
				if (strcmp(yytext, "-") == 0)
				{
					s1[contador].valor2 = 2;
				}
				if (strcmp(yytext, "*") == 0)
				{
					s1[contador].valor2 = 3;
				}
				if (strcmp(yytext, "/") == 0)
				{
					s1[contador].valor2 = 4;
				}
				if (strcmp(yytext, "%") == 0)
				{
					s1[contador].valor2 = 5;
				}
				printf("%d+", s1[contador].tipo);
				printf("%d\n", s1[contador].valor2);
				fprintf(fichero, "<%s,%d>\n", s1[contador].lexema, s1[contador].valor2);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;

				break;

			case OpRelacion:
				s1[contador].tipo = OpRelacion;
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lexema = "OpRelacion";
				s1[contador].lineaDondeEsta = yylineno;
				if (strcmp(yytext, "==") == 0)
				{
					s1[contador].valor2 = 1;
				}
				if (strcmp(yytext, "!=") == 0)
				{
					s1[contador].valor2 = 2;
				}
				if (strcmp(yytext, "<=") == 0)
				{
					s1[contador].valor2 = 3;
				}
				if (strcmp(yytext, ">=") == 0)
				{
					s1[contador].valor2 = 4;
				}
				if (strcmp(yytext, "<") == 0)
				{
					s1[contador].valor2 = 5;
				}
				if (strcmp(yytext, ">") == 0)
				{
					s1[contador].valor2 = 6;
				}

				printf("%d+", s1[contador].tipo);
				printf("%d\n", s1[contador].valor2);
				fprintf(fichero, "<%s,%d>\n", s1[contador].lexema, s1[contador].valor2);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;

				break;

			case OpLogico:
				s1[contador].tipo = OpLogico;
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lexema = "OpLogico";
				s1[contador].lineaDondeEsta = yylineno;
				if (strcmp(yytext, "&&") == 0)
				{
					s1[contador].valor2 = 1;
				}
				if (strcmp(yytext, "!") == 0)
				{
					s1[contador].valor2 = 2;
				}
				if (strcmp(yytext, "||") == 0)
				{
					s1[contador].valor2 = 3;
				}

				printf("%d+", s1[contador].tipo);
				printf("%d\n", s1[contador].valor2);
				fprintf(fichero, "<%s,%d>\n", s1[contador].lexema, s1[contador].valor2);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;

			case OpAsignacion:
				s1[contador].tipo = OpAsignacion;
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lexema = "OpAsignacion";
				s1[contador].lineaDondeEsta = yylineno;

				if (strcmp(yytext, "=") == 0)
				{
					s1[contador].valor2 = 1;
				}
				if (strcmp(yytext, "+=") == 0)
				{
					s1[contador].valor2 = 2;
				}
				if (strcmp(yytext, "-=") == 0)
				{
					s1[contador].valor2 = 3;
				}
				if (strcmp(yytext, "*=") == 0)
				{
					s1[contador].valor2 = 4;
				}
				if (strcmp(yytext, "/=") == 0)
				{
					s1[contador].valor2 = 5;
				}
				if (strcmp(yytext, "%=") == 0)
				{
					s1[contador].valor2 = 6;
				}
				if (strcmp(yytext, "&=") == 0)
				{
					s1[contador].valor2 = 7;
				}
				if (strcmp(yytext, "|=") == 0)
				{
					s1[contador].valor2 = 8;
				}

				printf("%d+", s1[contador].tipo);
				printf("%d\n", s1[contador].valor2);
				fprintf(fichero, "<%s,%d>\n", s1[contador].lexema, s1[contador].valor2);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;

			case OpAutoIncrementoDecremento:
				s1[contador].tipo = OpAutoIncrementoDecremento;
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lexema = "OpAutoIncrementoDecremento";
				s1[contador].lineaDondeEsta = yylineno;
				if (strcmp(yytext, "++") == 0)
				{
					s1[contador].valor2 = 1;
				}
				if (strcmp(yytext, "--") == 0)
				{
					s1[contador].valor2 = 2;
				}

				printf("%d+", s1[contador].tipo);
				printf("%d\n", s1[contador].valor2);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;

			case Llave:
				s1[contador].tipo = Llave;
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lexema = "Llave";
				s1[contador].lineaDondeEsta = yylineno;
				char aaaa;
				if (strcmp(yytext, "{") == 0)
				{
					s1[contador].valor2 = 1;
					aaaa = '1';

					fprintf(ficheroDraco, "<%d,%c>\n", s1[contador].tipo, aaaa);
				}
				if (strcmp(yytext, "}") == 0)
				{
					s1[contador].valor2 = 2;
					aaaa = '2';

					fprintf(ficheroDraco, "<%d,%c>\n", s1[contador].tipo, aaaa);
				}

				printf("%d+", s1[contador].tipo);
				printf("%d\n", s1[contador].valor2);
				fprintf(fichero, "<%s,%d>\n", s1[contador].lexema, s1[contador].valor2);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;

			case IF:
				s1[contador].tipo = IF;
				s1[contador].lexema = "if";
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case BOOLEAN:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = BOOLEAN;
				s1[contador].lexema = "boolean";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case BREAK:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = BREAK;
				s1[contador].lexema = "break";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case CASE:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = CASE;
				s1[contador].lexema = "case";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case STRING:
				s1[contador].tipo = STRING;
				s1[contador].lexema = yytext;
				s1[contador].lexemaSintactico = yytext;
				s1[contador].lineaDondeEsta = yylineno;
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case DEFAULT:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = DEFAULT;
				s1[contador].lexema = "defeault";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case DO:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = DO;
				s1[contador].lexema = "do";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case ELSE:
				s1[contador].tipo = ELSE;
				s1[contador].lexema = "else";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case FALSEE:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = FALSEE;
				s1[contador].lexema = "false";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case FOR:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = FOR;
				s1[contador].lexema = "for";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case FUNCTION:
				//Aqui es necesario usar la tabla de simbolos para almacenar datos 
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = FUNCTION;
				s1[contador].lexema = "function";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case INT:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = INT;
				s1[contador].lexema = "int";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case NULLL:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = NULLL;
				s1[contador].lexema = "null";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;;
				break;
			case INPUT:
				s1[contador].tipo = INPUT;
				s1[contador].lexema = "input";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case RETURN:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = RETURN;
				s1[contador].lexema = "return";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case SWITCH:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = SWITCH;
				s1[contador].lexema = "switch";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case TRUEE:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = TRUEE;
				s1[contador].lexema = "true";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case VAR:
				//Aqui es necesario usar la tabla de simbolos para almacenar datos 
				s1[contador].tipo = VAR;
				s1[contador].lexema = "var";
				s1[contador].lexemaSintactico = yytext;

				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,%d>\n", s1[contador].lexema, s1[contador].valor2);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case WHILE:
				s1[contador].tipo = WHILE;
				s1[contador].lexema = "while";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
			case PRINT:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = PRINT;
				s1[contador].lexema = "print";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;

			case CADENA:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = CADENA;
				s1[contador].lexema = "cadena";
				s1[contador].lineaDondeEsta = yylineno;
				fprintf(fichero, "<%s,%s>\n", s1[contador].lexema, yytext);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				printf("cadenaaaaaa\n");
				break;

			case CONSTENTERA:
				s1[contador].lexemaSintactico = yytext;
				s1[contador].tipo = CONSTENTERA;
				s1[contador].lexema = "constanteEntera";
				s1[contador].lineaDondeEsta = yylineno;
				printf("%d+", s1[contador].tipo);
				printf("%s\n", s1[contador].lexema);
				fprintf(fichero, "<%s,->\n", s1[contador].lexema);
				fprintf(ficheroDraco, "<%d,>\n", s1[contador].tipo);
				contador++;
				break;
		}
	}
	//cuando salgo del bucle escribo la tabla de simbolos

}





